/*
 * Andrew Koroluk
 */

import java.util.Scanner;

class Tri {
	public int divisors(int var) {
		int div=0;
		for(int i=1; i<=Math.sqrt(var); i++) {
			if(var%i==0) {
				div+=2;
			}
		}
		if(var%Math.sqrt(var)==0) {
			div--;
		}
		return div;
	}
}

public class euler12 {
    public static void main(String[] args) {
		Tri tri = new Tri();
		int prev=0, num=0;

		for(int i=1; num<=76577000; i++) {
			num = prev + i;
			prev = num;
			System.out.print(num + " - " + tri.divisors(num));
			new Scanner(System.in).nextLine();
			if(tri.divisors(num)>500) {
				break;
			}
		}
    }
}

/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/